const acorn = require('acorn');

const newIonizerPage = `function WaterIonizersPageComponent(){const c=[{name:"Kita Euphoria Water Ionizer",desc:"Advanced Alkaline Water Ionizer Machine featuring 7 platinum-coated titanium plates, automatic cleaning, multiple pH levels, and antioxidant-rich water."}];return o.jsx("div",{className:"py-24 bg-white min-h-screen",children:o.jsxs("div",{className:"mx-auto max-w-7xl px-6 lg:px-8",children:[o.jsx("h1",{className:"text-4xl font-bold tracking-tight text-gray-900 sm:text-5xl mb-6",children:"Water Ionizer Machines"}),o.jsx("p",{className:"text-lg text-gray-600 max-w-2xl mb-12 leading-relaxed",children:"Advanced Alkaline Water Ionizer Machines designed to transform ordinary drinking water into alkaline, antioxidant-rich water through electrolysis technology. Suitable for homes, wellness centers, offices, and health-conscious users seeking premium hydration solutions."}),o.jsx("div",{className:"grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-8 mt-12",children:c.map((r,d)=>o.jsxs("div",{className:"group relative border border-gray-200 rounded-2xl overflow-hidden bg-white shadow-sm hover:shadow-lg transition-all flex flex-col",children:[o.jsxs("div",{className:"aspect-[4/3] bg-gray-100 p-6 flex items-center justify-center overflow-hidden relative",children:[o.jsx("div",{className:"absolute inset-0 bg-gray-200 mix-blend-multiply opacity-20"}),o.jsx(ze,{to:"/product/"+encodeURIComponent(r.name),className:"h-full w-full flex items-center justify-center cursor-pointer relative z-10",children:o.jsx("img",{src:Il,alt:r.name,className:"h-full w-full object-contain mix-blend-darken transition-transform duration-500 group-hover:scale-110"})})]}),o.jsxs("div",{className:"p-6 flex flex-col flex-1",children:[o.jsx("h3",{className:"text-lg font-bold text-gray-900 mb-2",children:r.name}),o.jsx("p",{className:"text-sm text-gray-600 mb-6 flex-1",children:r.desc}),o.jsxs("div",{className:"mt-auto flex gap-2 w-full",children:[o.jsx(ze,{to:"/product/"+encodeURIComponent(r.name),className:"flex-1 text-center bg-white border border-[#1a2b66] text-[#1a2b66] font-semibold py-2.5 rounded-lg hover:bg-[#1a2b66] hover:text-white transition-colors text-sm",children:"View Details"}),o.jsx(ze,{to:"/contact",className:"flex-1 text-center bg-[#1a2b66] text-white font-semibold py-2.5 rounded-lg hover:bg-[#111e4a] transition-colors text-sm",children:"Get Quote"})]})]})]},d))})]})})}`;

try {
   acorn.parse(newIonizerPage, { ecmaVersion: 'latest', sourceType: 'module' });
   console.log("newIonizerPage parsed perfectly!");
} catch (e) {
   console.log("newIonizerPage ERROR: ", e);
}
